# Generated by Django 5.0.6 on 2024-08-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('UAT', 'UAT')], max_length=4)),
                ('name', models.CharField(blank=True, help_text='Optional name or description for the connection', max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
            ],
        ),
    ]
