# Generated by Django 5.0.6 on 2024-08-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binblocking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseconnection',
            old_name='table_name',
            new_name='DatabaseTNS',
        ),
    ]
