# Generated by Django 5.0.6 on 2024-08-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binblocking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name or description for the connection', max_length=100, null=True),
        ),
    ]
