# Generated by Django 5.0.6 on 2024-08-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binblocking', '0002_rename_table_name_databaseconnection_databasetns'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='table_name',
            field=models.CharField(default=1, help_text='Enter desired table name', max_length=255),
            preserve_default=False,
        ),
    ]
