# Generated by Django 5.0.6 on 2024-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('psp_name', models.CharField(max_length=100)),
                ('psp_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('schemes', models.CharField(max_length=100)),
                ('repeat', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('every', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
