# Generated by Django 5.0.6 on 2024-08-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_scheme_schemetype'),
        ('sender', '0002_remove_serverconfig_ip_address_serverconfig_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='scheme',
            field=models.ManyToManyField(to='bookings.scheme'),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheme_type',
            field=models.ManyToManyField(to='bookings.schemetype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sender.serverconfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='psp_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='psp_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schemetype',
            name='type_name',
            field=models.CharField(max_length=300),
        ),
    ]
