# Generated by Django 5.0.6 on 2024-08-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_booking_id_booking_scheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='psp_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.CharField(default=1, max_length=255, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
