# Generated by Django 5.0.6 on 2024-08-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_psp_id_booking_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='project_id',
        ),
    ]
