# Generated by Django 5.0.6 on 2024-07-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverconfig',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='hostname',
            field=models.CharField(default='default_hostname', max_length=255),
        ),
    ]
